@startuml
' See docs http://plantuml.com/sequence.html
'
' generate png:
' npm run puml

control api
database cache
database disk
control fileProcessor

api -> cache : readFile('example.json') // 1
cache -> disk : readFile('example.json')
disk -> fileProcessor : process('example.json', '{"x" : 1}')
fileProcessor -> cache : cache({x:1})
cache -> api: return {x:1}
... ... 
api -> cache : readFile('example.json') // 2
cache -> api: return {x:1}
... ... 
disk -> cache : file 'example.json' changed
... ... 
api -> cache : readFile('example.json')  // 3
cache -> disk : readFile('example.json')
disk -> fileProcessor : process('example.json', '{"a" : 9}')
fileProcessor -> cache : cache({a:9}) 
cache -> api: return {a:9}
... ... 
api -> cache : readFile('example.json') // 4
cache -> api: return {a:9}

@enduml